name: fakeaccount
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_credit_card: ^3.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  image_picker: ^0.8.4+10
  flutter_bloc: ^8.0.1
  screenshot: ^1.2.3
  share: ^2.0.4
  feature_discovery: ^0.14.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

























